### ISSUE TITLE
Watch development website on external devices

### ISSUE THREAD

**Issue by EmanuelSchreuder** [WP-Performance/press-wind#14]
On my local i'm using Laravel Homestead to develop my websites. 
Is it possible to watch the website you working on, on your mobile device?

I can't get this to work. Is there any workaround for this?

**Comment by ipatate** [comment]
hi, you can add --host in scripts in package.json:
```
    "dev": "cross-env APP_ENV=development vite --host & npm run watch:editor",
```

**Comment by ipatate** [comment]
no sorry, i can't help you. I don't know homestead.
