### ISSUE TITLE
Main.js problem

### ISSUE THREAD

**Issue by tagperfect** [WP-Performance/press-wind#20]
Tried the theme, but but got an error in the console, looks like the main.js file path compiled wrong and looks like this:

https://localhost:3000/wp-contentthemespress-wind/main.js?ver=1691594594

**Comment by tagperfect** [comment]
Ok, found bug. The enqueue method:
`wp_enqueue_script($slug, 'https://localhost:' . $port . '/wp-content' . get_wp_path($path) . '/main' . ($is_ts ? '.ts' : '.js'), [], strtotime('now'), true); `

Function `get_wp_path($path)` is removing slashes.

**Comment by ipatate** [comment]
i look that ASAP, thanks
