### ISSUE TITLE
Call to undefined function PressWind\\version() in presswind-plugin-main/vendor/wp-performance/presswind-assets/src/PWVite.php:242\nStack

### ISSUE THREAD

**Issue by rohit-ghoghari** [WP-Performance/press-wind#26]
We are facing an issue with the plugin file. "npm run build" successfully and also not getting any error with "npm run dev" but showing me the below error in a log file.

[Fri Mar 22 06:17:31.549343 2024] [proxy_fcgi:error] [pid 787:tid 133436110992960] [client 115.246.21.250:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function PressWind\\version() in /home/webbycrown/webapps/webbycrown-solutions/website/web/app/plugins/presswind-plugin-main/vendor/wp-performance/presswind-assets/src/PWVite.php:242\nStack trace:\n#0 /home/webbycrown/webapps/webbycrown-solutions/website/web/app/plugins/presswind-plugin-main/vendor/wp-performance/presswind-assets/src/PWVite.php(142): PressWind\\PWVite->set_script_prod()\n#1 /home/webbycrown/webapps/webbycrown-solutions/website/web/app/plugins/presswind-plugin-main/vendor/wp-performance/presswind-assets/src/PWVite.php(56): PressWind\\PWVite->set_script()\n#2 /home/webbycrown/webapps/webbycrown-solutions/website/web/app/plugins/presswind-plugin-main/vendor/wp-performance/presswind-assets/src/PWVite.php(75): PressWind\\PWVite->__construct()\n#3 /home/webbycrown/webapps/webbycrown-solutions/website/web/app/themes/webbycrown/functions.php(207): PressWind\\PWVite::init()\n#4 /home/webbycrown/webapps/webbycrown-solutions/website/web/w...', referer:

**Comment by ipatate** [comment]
hi, are you installed the plugin https://github.com/WP-Performance/presswind-plugin ?

**Comment by rohit-ghoghari** [comment]
Hi @ipatate,

Thank you for your response but finally I have fixed this issue from my end. There was a data type-related issue in the version format. Thanks again.
