### ISSUE TITLE
100% compatible with Gutenberg?

### ISSUE THREAD

**Issue by lukasz-gorski** [WP-Performance/press-wind#8]
100% compatible with Gutenberg ? How come if there is no editor.js file and 0 to support Gutenberg.

**Comment by ipatate** [comment]
hello, it's starter, you can add all stuffs you want. 
For Gutenberg, you have the file theme.json.
If you want use FSE, you have a branch for that. https://github.com/WP-Performance/press-wind/tree/FSE
Personally, i have multiple sites with this starter and i use always FSE for all. 
This site by exemple, use this stater and FSE https://wp-performance.com/

**Comment by ipatate** [comment]
hi @lukasz-gorski, now you have js files for editor. => https://presswind-doc.wp-performance.com/structure/admin/

**Comment by lukasz-gorski** [comment]
Hi @ipatate .

Thank you for your time to solve that issue. So I see that instead 

import { unregisterBlockStyle } from '@wordpress/blocks';
registerBlockStyle( 'totaldigital/white-boxes', []);

need to use just:

wp.blocks.unregisterBlockStyle('core/button', []);

Looks like a method, but a bit bypass. Well, if it works... ;) 

I was trying to use some packages to make them external from config, but failed.

Anyway, awesome work, thanks.
